### ISSUE TITLE
NPE Exception if breadcrumbbar is used

### ISSUE THREAD

**Issue by sgrebing** [mattulbrich/dive#138]
A NPE Exception is thrown when the breadcrumbbar is used. When digging deeper, it appears that Scene is null for the HBox containing the breadcrumbbar. 
````
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.controls/com.sun.javafx.scene.control.skin.Utils.removeMnemonics(Utils.java:743)
        at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by mattulbrich** [comment]
Have not observed that recently. I will close it.

**Comment by SpringVaS** [comment]
I still experience the bug. If no one would mind, I will open it up again and assign myself.
