### ISSUE TITLE
The example can be edited but not reloaded

### ISSUE THREAD

**Issue by mattulbrich** [mattulbrich/dive#172]
The example file ("Open Example" on startup page) can be modified, can be saved, but not "Refresh"ed.

Then one receives an exception:

````
java.nio.file.NoSuchFileException: /home/mattias/sync/eclipse/dive/ListExample/ListExample/AlgoVerList.dfy
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
	at edu.kit.iti.algover.editor.EditorController.fileToString(EditorController.java:274)
	at edu.kit.iti.algover.editor.EditorController.viewFile(EditorController.java:150)
	at edu.kit.iti.algover.editor.EditorController.showException(EditorController.java:216)
	at edu.kit.iti.algover.MainController.lambda$refreshHelper$18(MainController.java:513)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1358)
	at javafx.concurrent.Task.setState(Task.java:709)
	at javafx.concurrent.Task$TaskCallable.lambda$call$2(Task.java:1455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by mattulbrich** [comment]
Astonishingly, this exception is only thrown if there is a syntax error in the program.

**Comment by SpringVaS** [comment]
Working on it. I have a fix for the loading. But the behavior differs between opening the project via "Open Project" or "Load Example". Curiosities when choosing "Load Example".
