### ISSUE TITLE
Lemmas containing composed sorts are not parsed correctly

### ISSUE THREAD

**Issue by mattulbrich** [mattulbrich/dive#192]
The following lemma raises an exception.

    lemma l1(s: seq<int>) ensures (|s|==|s|) {}

The stacktrace is essentially:
````
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at edu.kit.iti.algover.util.Util$ReadOnlyArrayList.get(Util.java:457)
	at edu.kit.iti.algover.term.builder.TreeTermTranslator.buildCardinality(TreeTermTranslator.java:868)
	at edu.kit.iti.algover.term.builder.TreeTermTranslator.build(TreeTermTranslator.java:467)
	at edu.kit.iti.algover.rules.DafnyRuleUtil.generateRule(DafnyRuleUtil.java:175)
	at edu.kit.iti.algover.rules.DafnyRuleUtil.generateDafnyRules(DafnyRuleUtil.java:70)
	at edu.kit.iti.algover.project.Project.makeLemmaProofRules(Project.java:442)
````

**Comment by mattulbrich** [comment]
I have added a failing test case on the branch `fix-192`.

**Comment by JonasKlamroth** [comment]
@mattulbrich i had to adapt you testcase slightly but i figured that this is still the fix you were looking for. can you confirm?
